name: Build Image

on:
  workflow_dispatch:
    inputs:
      release:
        type: string
        required: true
        description: 'Kubectl release version'
        default: '1.32.5'

jobs:
  build:
    name: Build Image
    runs-on: self-hosted
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=v${{ github.event.inputs.release }}-tumbleweed

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          provenance: false
          build-args: |
            KUBECTL_VERSION=${{ github.event.inputs.release }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Cleanup environment
        if: ${{ always() }}
        run: |
          docker image prune --force --all
